### ISSUE TITLE
[TVD]: KWin Crashes when using the the script

### ISSUE THREAD

**Issue by LechTheMitch** [Ubiquitine/kwin-scripts#3]
KWin often crashes when using this script, can you please tell me if there are any logs I can provide.

Thank You for your work

**Comment by Ubiquitine** [comment]
> KWin often crashes when using this script, can you please tell me if there are any logs I can provide.
> 
> Thank You for your work

Could you please be more specific?

Which script exactly do you use? Do you use the latest version of the script?
What is your system specifications? Distribution, plasma version, Xorg or Wayland, GPU? 

Do you have any other KWin script enabled? If yes, did you try to disable other scripts to exclude conflicts between scripts?

In general, you can enable debugging by uncommenting the second line in `./local/share/kwin/scripts/SCRIPT_NAME/content/code/main.js` , the "print" line in log function. After that you can see the logs with `journalctl -f QT_CATEGORY=js QT_CATEGORY=kwin_scripting`

**Comment by LechTheMitch** [comment]
> > KWin often crashes when using this script, can you please tell me if there are any logs I can provide.
> > 
> > Thank You for your work
> 
> Could you please be more specific?
> 
> Which script exactly do you use? Do you use the latest version of the script?
> What is your system specifications? Distribution, plasma version, Xorg or Wayland, GPU? 
> 
> Do you have any other KWin script enabled? If yes, did you try to disable other scripts to exclude conflicts between scripts?
> 
> In general, you can enable debugging by uncommenting the second line in `./local/share/kwin/scripts/SCRIPT_NAME/content/code/main.js` , the "print" line in log function. After that you can see the logs with `journalctl -f QT_CATEGORY=js QT_CATEGORY=kwin_scripting`

Oh i am sorry for not being specific github made me choose the name of the script from a list of four so i thought it showed up for you.
As for the script i am using it's the Temporary Virtual Desktops one and i was using it with MACsimize6, i tried disabling it but still the issue persisted even on a clean install of arch was using fedora before, I will try to send logs as soon as possible sorry for replying late as i am quite busy these days.

GPU: Nvidia RTX 3070 Mobile
Graphics Platform: Wayland
KDE Version: Plasma 6
Distro: Arch Linux
