### ISSUE TITLE
[TVD]: Ghost application in the first virtual desktop

### ISSUE THREAD

**Issue by SamuXzX** [Ubiquitine/kwin-scripts#7]
When Temporary Virtual Desktops is enabled, the first virtual desktop is always filled by an additional, invisible application that I cannot recognize. This ghost application can't be focused nor moved across virtual desktops, so my first virtual desktop is always available only by half.

I'm on KDE Neon 6.0 with Plasma 6.0.4 and some version ago I saw an application appearing in the Overview together with other open applications, but it was invisible in the actual desktop. Such ghost application disappeared in some recent version and now I see the same icon in the System Tray as "Wayland to X11 Video bridge". Maybe it's this one that gets counted as an open application?

**Comment by Ubiquitine** [comment]
The script itself does not create any windows, as well as does not make any changes on windows.
It is only checking if virtual desktop has any windows on it and if not - removes this virtual desktop.

To try and improve script logic I added checks for "normal" windows for both monitoring the changes and checking if desktop is empty. This might also resolve those crashes you described in [this issues](https://github.com/Ubiquitine/kwin-scripts/issues/6)

Please test the version from the branch **7-tvd-ghost-application-in-the-first-virtual-desktop**. Follow the instruction from README to upgrade the script with helper.sh tool.

**Comment by SamuXzX** [comment]
I tested it and it seems it corrected both problems.
