### ISSUE TITLE
[MACsimize6]: Games not detected

### ISSUE THREAD

**Issue by ProjectInfinity** [Ubiquitine/kwin-scripts#9]
Love this but unfortunately it seems like games launched from Steam (flatpak) is not being detected. Neither fullscreen borderless or exclusive fullscreen seems to trigger MACsimize. While the tool on its own is neat, this would've been the one thing that really sold it for me.

**Comment by Ubiquitine** [comment]
Thank you for reporting this issue.
Indeed Steam games that start in full-screen are not being moved to a separate VD, regardless of flatpak. 
Let me check why exactly. The script should work for every "normal" window that can be maximized or full-screened. maybe Steam games windows lack some of those properties.

**Comment by Ubiquitine** [comment]
Steam games windows are not maximizable, but full-screenable. That is why the scrip was ignoring them.
v0.2.4 has a fix for this.

**Comment by ProjectInfinity** [comment]
Thanks for the swift reply and fix. It does indeed work! One question, regarding the naming is it possible to use the window title? I assume that in this case it is not the window title being used :)

![image](https://github.com/Ubiquitine/kwin-scripts/assets/593870/4b7e2f04-006a-44bc-a929-2cd8e2b16ddc)

**Comment by Ubiquitine** [comment]
Application name is used for naming a new virtual desktop. 
Window title might change, e.g. web browser change window title according to active tab, terminal emulators change window title depending on running command, etc... 
I picked more persistent identification for the VD name.

**Comment by Ubiquitine** [comment]
Actually....
Why not use window title/caption and update the VD name when window caption changes. 
So I implemented it in v0.2.5 of the script.
